[results]
path = "results"

[app.Batch]
# The ratio between read & write operations.
# 0.0 - Only write
# 1.0 - Only read
rw = 1.0
# Total number of blocks which are present in the storage stack.
size = 40_000

# How many reqs are submitted to the stack per batch.
reqs_per_batch = 3
iteration = 10_000_000
interval = "10ms"

[app.Batch.pattern.Zipf]
# Theta for Zipfian Distribution
theta = 0.99
seed = 54321

#[app.Batch.pattern.Uniform]
#seed = 54321

[cache]
algorithm = "Noop"
capacity = 0
device = "bress-vol1"

[placement.Frequency]
interval = "30min"
reactiveness = 100
decay = 0.05

#[placement.Noop]

# Which devices will be used.
[devices]

[devices.bress-vol1]
kind = "bress-vol1"
capacity = 30_000

[devices.bress-vol2]
kind = "bress-vol2"
capacity = 10_000

[devices.ants-nvme]
kind = "ants-nvme"
capacity = 5_000

#[devices.ants-hdd]
#kind = "ants-hdd"
#capacity = 10_000
#
#[devices.ants-ssd]
#kind = "ants-ssd"
#capacity = 10_000
