[results]
path = "results"

[app.Batch]
# The ratio between read & write operations.
# 0.0 - Only write
# 1.0 - Only read
rw = 0.5
# Total number of blocks which are present in the storage stack.
size = 1_000

# How many reqs are submitted to the stack per batch.
reqs_per_batch = 100
iteration = 100
interval = "3s"

[app.Batch.pattern.Zipf]
# Theta for Zipfian Distribution
theta = 0.99
seed = 54321

# [app.Batch.pattern.Uniform]
# seed = 54321

[cache]
algorithm = "Lru"
capacity = 32
device = "DRAM"

[placement.Frequency]
interval = "30min"
reactiveness = 100
decay = 0.05

#[placement.Noop]


# Which devices will be used.
[devices]

[devices.optane_pmem]
kind = "Intel_Optane_PMem_100"
# Total size of device in number of blocks.
capacity = 20_000

# [devices.optane_ssd]
# kind = "Intel_Optane_SSD_DC_P4800X"
# capacity = 100_000

[devices.kioxia_ssd_0]
kind = "KIOXIA_CM7"
capacity = 100_000

[devices.my-own-hdd]
kind = { Custom = "cluster-old-hdd" }
capacity = 999999

# [devices.my-own-hdd1]
# kind = { Custom = "cluster-old-hdd" }
# capacity = 999999
# 
# 
# [devices.my-own-hdd2]
# kind = { Custom = "cluster-old-hdd" }
# capacity = 999999


# [devices.spinny_boy]
# kind = "Western_Digital_WD5000AAKS"
# capacity = 123456
