[package]
name = "test-access"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fmmap = "0.3.3"
libc = "0.2.148"
rand = "0.8.5"
